### ISSUE TITLE
Testing the plugin, it randomly crashes sometimes while trying to execute.

### ISSUE THREAD

**Issue by GuardianWorld** [cda-tum/quicksim-siqad-plugin#23]
Good night, I'm using the QuickSim plugin to simulate the connection of 3 gates (AND-> OR <- AND) and sometimes (Like, 50-60% of the times) it just, crashes with exit Code 11. 
Trying to simulate with a bigger circuit (6 gates connected), i had no luck, having only crashes.
(Around 40-50+ DBs it starts crashing and around 100+ it has a hard time trying to give back a result once.)
I don't know what is going on, but image below.

System: Ubuntu 20.04.
Mu: -0.32
Using the SiQAD interface.

![image](https://user-images.githubusercontent.com/12464623/220490349-5a87b7b8-ab2c-44a6-a9f0-58e8e0605a0e.png)

**Comment by Drewniok** [comment]
Hi Emanuel,

Wonderful that you already use `QuickSim` in SiQAD! Thanks for your important and helpful feedback! 

First of all, I have to mention that `QuickSim` is optimized for gate layouts (~ 20 – 30 SiDBs). The simulation of larger layouts is still under investigation. However, I can already give you some hints:

1.)  This error occurs when no physically valid charge distribution is found. Thanks for pointing this out, we will implement a more meaningful error description. 
2.)  If you use a few connected gates, you should play with the number of `iteration steps`. For three connected gates, I would recommend 1.000 iteration steps (maybe a slightly smaller alpha value, but keep it at 0.7 for now). But again, detailed study is still in progress. You could increase the number of iteration steps even more. This will increase the accuracy but also the simulation runtime.
3.)  If `QuickSim` has problems to find a solution, check if the connection of the single gates is correct, i.e. the wire between the gates works. If µ is too small or too large, the SiDB wire starts to fail since there are too many or too few electrons available for the Binary Dot Logic. However, µ = -0.32 eV should be fine. 


Thanks again for pointing out the issues and for your feedback. It helps us a lot to improve the simulation engine `QuickSim` even further. 

If you still have problems, don't hesitate to contact us. We will be happy to help you!
